spring.application.name=exam-be

app.name=exam-be
app.description=Backend para parcial Spring Boot
app.version=0.1.0-SNAPSHOT
app.url=http://localhost:8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:examdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logs
logging.level.org.springframework=WARN